---
abstract: 'A Nagios NRPE implementation in pure perl'
author:
  - 'Andreas Marschke'
  - 'Sven Nierlein'
  - 'Franz Skale'
  - 'Johan Carlquist <jocar@su.se>'
  - 'Christian Biamont <cbeam@su.se>'
  - 'Micke Nordin <mikael.nordin@su.se>'
build_requires:
  Test::More: 0
  Test::Pod::Coverage: 0
configure_requires:
  Module::Build: 0.31
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nagios-NRPE
no_index:
  directory:
    - t
    - xt
provides:
  Nagios::NRPE:
    file: lib/Nagios/NRPE.pm
    version: v1.0.3
  Nagios::NRPE::Client:
    file: lib/Nagios/NRPE/Client.pm
    version: v1.0.3
  Nagios::NRPE::Daemon:
    file: lib/Nagios/NRPE/Daemon.pm
    version: v1.0.3
  Nagios::NRPE::Packet:
    file: lib/Nagios/NRPE/Packet.pm
    version: v1.0.3
  Nagios::NRPE::Utils:
    file: lib/Nagios/NRPE/Utils.pm
    version: v1.0.3
requires:
  Convert::Binary::C: 0
  Digest::CRC: 0
  IO::Socket: 0
  IO::Socket::INET6: 0
  constant: 0
  perl: 5.010_000
resources:
  homepage: http://github.com/stockholmuniversity/nagios-nrpe
  license: http://dev.perl.org/licenses/
  repository: git://github.com/stockholmuniversity/nagios-nrpe.git
version: v1.0.3
